[package]
name = "rocket-simples"
version = "0.1.0"
authors = ["vapvin <tpehdj12@daum.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
